# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_d545678cb00b44a8acc7141974c90e21 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_ecfe3e4a709546c1af398c427d269d98 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d545678cb00b44a8acc7141974c90e21 }}/codecoach:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'codecoach'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_02d3cdd87bf440ba841e418ee16c68f6 }}
          images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_d545678cb00b44a8acc7141974c90e21 }}/codecoach:${{ github.sha }}'
